# POST http://localhost:4000/signup 
# Content-Type: application/json

# {
#     "fullName":"test",
#     "email": "test@test.com",
#     "password": "Test123"
# }

POST http://localhost:4000/signin 
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test123"
}