# POST http://localhost:4000/signup 
# Content-Type: application/json

# {
#     "fullName":"test",
#     "email": "test@test.com",
#     "password": "Test123"
# }
#   "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmI1ZWNmNmI3N2RhMmU2OGE4NDhkNyIsImlhdCI6MTcwNzEyMjYzMX0.j6lTH5PakYrvEpg5wIpoHCS6EUdLQTASS3jI77b1LOI",
# POST http://localhost:4000/signin 
# Content-Type: application/json

# {
#     "email": "ram@gmail.com",
#     "password": "Test123"
# }

# POST http://localhost:4000/create-blog 
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmI1ZWNmNmI3N2RhMmU2OGE4NDhkNyIsImlhdCI6MTcwNzEyMjYzMX0.j6lTH5PakYrvEpg5wIpoHCS6EUdLQTASS3jI77b1LOI
# Content-Type: application/json

# {
#     "title": "Test Title",
#     "banner":"http://test.com",
#     "des":"Description",
#     "content":{
#         "blocks":[1,3,2]
#     },
#     "tags":["Test","new"]
# }
GET http://localhost:4000/latest-blogs